### ISSUE TITLE
Good idea

### ISSUE THREAD

**Issue by spacejack** [cpylua/vscode-language-postcss#1]
I think it's a good idea to have a public repo for this. I was using the `postcss-sugarss-language` plugin but it recently broke for nesting with `&`.

One difference I see between this and the `PostCSS Syntax` plugin is that this one does not show pcss icons in the file explorer. Eg:

![pcss-icons-screenshot](https://user-images.githubusercontent.com/11592867/35761119-227145dc-0853-11e8-831c-847b92dbcffb.png)

**Comment by cpylua** [comment]
Fixed!

The language id is case sensitive in vscode.  Changed `PostCSS` to `postcss`.

**Comment by spacejack** [comment]
Thanks!
