### ISSUE TITLE
There is no formatter for 'postcss'-files installed

### ISSUE THREAD

**Issue by ilyar** [cpylua/vscode-language-postcss#5]
If press `Ctrl` + `Shift` + `I` i got: "There is no formatter for 'postcss'-files installed".
How can this be fixed, can there be another extension for this, or should it be implemented here?

**Comment by cpylua** [comment]
I use [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode). 

There are other [extensions](https://marketplace.visualstudio.com/search?term=css&target=VSCode&category=Formatters&sortBy=Relevance) that does the same thing, e.g. [js-beautify](https://github.com/HookyQR/VSCodeBeautify). Take a look and choose one.

**Comment by ilyar** [comment]
Thank you
