### ISSUE TITLE
CSS comments

### ISSUE THREAD

**Issue by timv88** [cpylua/vscode-language-postcss#6]
First of all, thanks for this vscode plugin. It's the only PostCSS plugin that recognizes property lookups, which is why I'm using it.

That being said, I'm facing some issues with `//` based comments when using vscode's keyboard shortcut. `//` comments are invalid CSS and don't play nicely with [stylelinter](https://stylelint.io/user-guide/rules/no-invalid-double-slash-comments/).

I tried looking around for how I can override vscode to always use `/* */` based comments but no luck. Do you know of a way I can do that? Or is it maybe possible to use `/* */` based comments by default for this plugin? (like `postcss-sugarss-language` does)

Or perhaps you have another suggestion for the problem I'm facing.

**Comment by timv88** [comment]
Thanks for your reply @cpylua. 

I ended up using [postcss-scss](https://github.com/postcss/postcss-scss) as my parser (which transforms all `//` comments into `/* */`) and turning off `no-invalid-double-slash-comments`. This works great for the resulting CSS.

Unfortunately stylelint is still applying linting rules to the content of my `//` comments in vscode:
![image](https://user-images.githubusercontent.com/1164786/43313825-7797e418-9191-11e8-92c3-da68579737dc.png) 
but that's a stylelint specific issue ` ¯\_(ツ)_/¯`

**Comment by kswedberg** [comment]
@cpylua Is it possible to just remove `"lineComment": "//",` in the language configuration file? That's what the Vetur extension does, and it seems to work well (https://github.com/vuejs/vetur/blob/master/languages/vue-postcss-language-configuration.json)

**Comment by cpylua** [comment]
@kswedberg  Thanks for the hint, you can try the new version `1.1.0`.

**Comment by kswedberg** [comment]
1.1.0 is working great. thanks for the update!
