### ISSUE TITLE
Line comments as /* */ instead of //

### ISSUE THREAD

**Issue by teddybradford** [cpylua/vscode-language-postcss#7]
By default it appears that cmd+/ comments the current line with two slashes `//` rather than slash asterisk `/* [line] */`.

I believe the former is invalid CSS, while the latter is valid.

Is there a way to disable the double slash comment in favor of the slash asterisk?

**Comment by KidkArolis** [comment]
See #8 for a short term fix and discussion.

**Comment by cpylua** [comment]
See #6 

Line comment has changed to `/* */` since version `1.1.0`.
