### ISSUE TITLE
Add support for `.stylelintrc.json` files

### ISSUE THREAD

**Issue by kripod** [cpylua/vscode-language-postcss#9]
Config files with extensions [are supported by stylelint](https://stylelint.io/user-guide/configuration/#loading-the-configuration-object), providing easier interpretation for text editors. Please consider loading the configuration of stylelint with [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)!

**Comment by cpylua** [comment]
`vscode-language-postcss` only adds syntax highlighting to postcss files. Can you elaborate why it is related to stylelint?

**Comment by kripod** [comment]
Because according to the readme, it is already recommended to use this plugin with stylelint.

**Comment by cpylua** [comment]
Well, this plugin does not rely on stylelint, you can use any valid file name for your stylelint config.
